#!/bin/bash
if [[ -e "/usr/bin/dtmenu" ]]; then
dtmenu
else
{
rm -f /usr/bin/proxy
apt install lolcat -y &>/dev/null
curl -s -L -o /usr/bin/dtmenu https://github.com/Penguinehis/DtWithMAIN/raw/main/$(uname -i)/dtmenu
curl -s -L -o /usr/bin/proxy https://github.com/Penguinehis/DtWithMAIN/raw/main/$(uname -i)/proxy
chmod +x /usr/bin/dtmenu /usr/bin/proxy
echo "Instalado com sucesso pequeno gafanhoto!" | lolcat
sleep 3
dtmenu
}
fi